### ISSUE TITLE
Annotate LEDs

### ISSUE THREAD

**Issue by morgenmuesli** [morgenmuesli/LED-Detection#13]
## Feature 
As a User I want to have a possibility to mark LEDs with a Bounding Box.

## Reason
Those Bounding Boxes are the ROI for detecting  LED states.

## Criteria
- [ ] Mark LEDs with rectangle
- [ ] Notate them with an ID 
- [ ] store annotations in a file

**Comment by olfarmer** [comment]
Duplicate issue
