### ISSUE TITLE
LED clones on redo

### ISSUE THREAD

**Issue by olfarmer** [morgenmuesli/LED-Detection#37]
Steps to recreate:

1. Place LED
2. Undo
3. Resize Window
4. Redo

Unwanted behavior: more than one led in the LED information bar, actual LED in top left corner instead of supposed to be position

**Comment by morgenmuesli** [comment]
I use issue-4 branch as origin.

**Comment by olfarmer** [comment]
I can not reproduce this behaviour in the current refactored version in https://github.com/morgenmuesli/LED-Detection/commit/a0067257192dcde2f5ff73166e582011c65b19bc. Maybe due to the changes in how LEDs are being placed the bug solved.
