### ISSUE TITLE
Led relative coordinates

### ISSUE THREAD

**Issue by olfarmer** [morgenmuesli/LED-Detection#39]
Storing the coordinates immediately with their relative coordinates seems unpractical as only the absolute coordinates are needed during run time.

Currently is problem is prevented by the flag in the  by following line: 

https://github.com/morgenmuesli/LED-Detection/blob/1d17549c7c4606d7d539f3dc87b6e5d43bfd8d72/src/BDG/coordinator/edit_handler.py#L49

but obviously the coordinates are not relative and therefore are not correct on saving.

Why not make them relative on saving and not before?

**Comment by morgenmuesli** [comment]
I decided to save the exact coordinates instead of the relative ones, because otherwise the information where the Upper Left Corner is located is lost or has to be saved additionally.

I add a utilty function for transforming corners
