### ISSUE TITLE
Board Pose Correction

### ISSUE THREAD

**Issue by morgenmuesli** [morgenmuesli/LED-Detection#7]
## Feature
As a Developer
I want a module which corrects the captured board by its pose and scaling.
## Reason
With that it is easier to detect the LEDs by their coordinates

## Criteria:
- [ ] Feature detection by reference image
- [ ] 3d Pose estimation
- [ ] Scaling of the image
- [ ] rotation of the image
- [ ] Transforming

**Comment by olfarmer** [comment]
With SURF this is no longer necessary
